
name: MAS_coding
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh==2.2.1
  - datashader==0.11.1
  - holoviews==1.13.4
  - hvplot==0.4.0
  - matplotlib==3.2.2
  - numpy==1.19.1
  - pandas==1.1.3
  - xarray==0.16.1
  - scipy==1.5.2
  - jupyterlab==2.2.6
  - ipykernel==5.3.4
  - cartopy==0.18.0
